spring.application.name=airbnb

# DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.username=postgres
spring.datasource.password=1234

server.servlet.context-path=/api/v1